from .get_token import get_bot_token
from .new_skillbox_chat import add_new_skillbox_chat
from .get_list_admins import get_bot_admins
from .add_admin import add_new_admin
from .get_password import get_bot_password
from .set_password import set_bot_password
from .del_admin import del_admin
from .get_list_user_group import get_list_user_group
from .set_moderator_chat import set_moderator_chat